name: Deploy Frontend

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying PocketBuddy Frontend..."
            cd /home/ubuntu/var/www/PocketBuddy-Frontend

            git pull origin dev
            npm install --force
            npm run build

            echo "Frontend deployment completed!"
            
